Exception:
ValueError: I/O operation on closed file.