Exception:
ValueError: Intentional failure for testing.

Logging:
WARNING	ordeq.nodes	Creating a view, as no outputs were provided for node 'logger_hook_custom_level_and_logger:fail'. Views are in pre-release, functionality may break without notice. Use @node(outputs=...) to create a regular node. 
ERROR	custom_logger	Called 'before_node_run' with args: (Node(name=logger_hook_custom_level_and_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
INFO	ordeq.io	Loading Literal('name')
INFO	ordeq.runner	Running node Node(name=logger_hook_custom_level_and_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)])
ERROR	custom_logger	Called 'after_node_run' with args: (Node(name=logger_hook_custom_level_and_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
ERROR	custom_logger	Called 'before_node_run' with args: (View(name=logger_hook_custom_level_and_logger:fail),)
INFO	ordeq.runner	Running node View(name=logger_hook_custom_level_and_logger:fail)
ERROR	custom_logger	Called 'on_node_call_error' with args: (View(name=logger_hook_custom_level_and_logger:fail), ValueError('Intentional failure for testing.'))